title: Kittabun Sukkasem
description: "Mobile Developer — Flutter / iOS (Swift) / Android (Kotlin) | Full-stack (Go, Node.js)"
logo: /profile.png
show_downloads: false
theme: jekyll-theme-minimal

defaults:
  - scope:
      path: ""
    values:
      layout: default
